version: '3'
services:
  api:
    image: mateusleonardi/dotnetcore:latest
    # depends_on:
    #   - database
    environment:
      DEBUG: 'true'
    ports:
      - "5000:5000"
    # volumes:
    #   - ./../:/code
    # command: bash "cd /var/app && dotnet run"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.10'
          memory: 512M